Feature scaling

In [3]:
import numpy as np
x = np.array([1.2, 2.0, 2.8, 3.6, 4.5, 5.1, 6.0, 6.7])
y = np.array([8.5, 11.1, 13.9, 16.2, 19.8, 21.4, 23.9, 26.1])

Standardization (Z-score scaling)

In [8]:
mean = x.mean()
std = x.std()
if std == 0 :
  std = 1

x_scaled = (x-mean)/std
print(x_scaled)

Normalization (Min-Max scaling)

In [10]:
max = x.max()
min = x.min()

x_scaled = (x-min)/(max-min)
print(x_scaled)

[0.         0.14545455 0.29090909 0.43636364 0.6        0.70909091
 0.87272727 1.        ]


Handling categorical variables

One-Hot Encoding

In [14]:
colors = np.array([     # sample dataset
    "red", "blue", "green", "red", "yellow",
    "blue", "green", "red", "yellow", "blue",
    "green", "red", "blue", "yellow", "green",
    "red", "blue", "green", "yellow", "red",
    "blue", "green", "yellow", "red", "blue",
    "green", "yellow", "red", "blue", "green"
])


In [16]:
def one_hot_encoding(x):
  categories = np.unique(x)

  cat_to_index = {cat : idx for idx , cat in enumerate(categories)}

  one_hot = np.zeros((x.shape[0] , categories.shape[0]))

  for i , value in enumerate(x):
    one_hot[i , cat_to_index[value]] = 1
  return one_hot

print(one_hot_encoding(colors))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
